name: CI/CD Deployment Pipeline

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  notify-start:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Teams - Deployment Started
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "Deployment Started",
            "title": "Deployment Started",
            "text": "Backend CI has started."
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
    deploy:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Deployment (Placeholder)
      - name: Deployment Step
        run: |
          echo "Deploying application..."
          sleep 15
          echo "Deployment done"

      #  Deployment Completed
      - name: Notify Teams - Deployment Completed
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "2EB886",
            "summary": "Deployment Completed",
            "title": "Deployment Completed",
            "text": "Deployment finished successfully."
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

