name: CI/CD Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Deployment Started
      - name: Notify Teams - Deployment Started
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "Deployment Started",
            "title": "Deployment Started",
            "text": "CI/CD pipeline deployment has started."
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

      #  Deployment (Placeholder)
      - name: Deployment Step
        run: |
          echo "Deploying application..."
          sleep 10
          echo "Deployment done"

      #  Deployment Completed
      - name: Notify Teams - Deployment Completed
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "2EB886",
            "summary": "Deployment Completed",
            "title": "Deployment Completed",
            "text": "Deployment finished successfully."
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

