name: CI/CD Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #  Deployment Started
      - name: Notify Teams - Deployment Started
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "text": " Deployment STARTED"
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

      #  Deployment (Placeholder)
      - name: Deployment Step
        run: |
          echo "Deploying application..."
          sleep 10
          echo "Deployment done"

      #  Deployment Completed
      - name: Notify Teams - Deployment Completed
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "text": " Deployment COMPLETED"
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

